"""
GraphState definition for LangGraph multi-agent system.
Defines the state structure that flows through the agent graph.
"""
from typing import TypedDict, Optional, List, Dict, Any
from plotly.graph_objects import Figure


class GraphState(TypedDict):
    """
    State structure for the LangGraph agent system.
    
    Attributes:
        query: User's natural language query
        plan: Execution plan generated by supervisor
        code: Generated SQL or Python code
        result: Query execution results (DataFrame, dict, etc.)
        visuals: Optional Plotly/Matplotlib figure object
        message_history: Conversation history for context
        intent: Detected intent from semantic router
        column_names: Optional list of column names extracted from SQL query
        code_type: Optional string indicating code type ("python" or "sql")
        sql_query: Optional SQL query string (for explainability)
        python_code: Optional Python code string (for explainability)
        chart_type: Optional chart type string (bar, pie, line, scatter)
        sql_result_df: Optional DataFrame from SQL query (for chart explainability)
    """
    query: str
    plan: Optional[str]
    code: Optional[str]
    result: Optional[Any]
    visuals: Optional[Figure]
    message_history: List[Dict[str, str]]
    intent: Optional[str]
    column_names: Optional[List[str]]
    code_type: Optional[str]
    sql_query: Optional[str]
    python_code: Optional[str]
    chart_type: Optional[str]
    sql_result_df: Optional[Any]

